#This tool intends that you have a the alias 'sd=". sd"' set in your .bashrc or whatever silly shell you happen to be using

stored="${HOME}/.local/bin/.sd"
#I like using files instead of environment variables because environment variables are weird. everything is a file right
#Its probably bad practice but like. this is my script DUDE

#Check if the file is funky
if [[ ! -f "${stored}" || `wc -l "${stored}" | tr -dc 0-9` -ne 3 ]]; then
	echo ""${stored}" file incorrect length or not found, recreating"
	echo -e "# This file is generated by s.
saved directory = 
previous directory = " > "${stored}"
fi

savedDir=`sed -n '2p' "${stored}"`
savedDir=/"${savedDir:19}"
prevDir=`sed -n '3p' "${stored}"`
prevDir=/"${prevDir:22}"

#Set saved directory
if [ "$1" == "." ]; then
	sed -i "2s,.*,saved directory = `pwd`," "${stored}"

#Print saved directory
elif [ "$1" == "-p" ] || [ "$1" == "--print" ]; then
	echo saved: "${savedDir}"
	echo previous: "${prevDir}"

#Default, go to saved directory
elif [ -z "$1" ]; then
	#If current directory is the same as saved, go back to previous
	if [ ${savedDir} == `pwd` ]; then
		cd "${prevDir}"
	else
		sed -i "3s,.*,previous directory = `pwd`," "${stored}"
		cd "${savedDir}"
	fi
#Go to previous directory
elif [ "$1" == "-b" ] || [ "$1" == "--back" ]; then
	cd "${prevDir}"

#help!
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo -e "sd: A simple tool to swap between saved directories.
USAGE:
-------
'sd .' will automatically save the current directory.
'sd [dir]' will manually saved a specified directory, [dir]
'sd' will go to the saved directory. If your current directory is the saved directory, instead go back to previous directory.
'sd -b' will go to the previous directory regardless of current directory.

OPTIONS:
--------
-b, --back        go to previous directory
-p, --print       print saved directory
-h, --help        print this message"

#Manually set saved directory (who tf would use this)
else
	sed -i "2s,.*,saved directory = `"$1"`," "${stored}"
fi
